Anton/feature/search
Simple2B/TenKabel_be pull request #9
Opened 2023-05-23 11:12 UTC by sa1am8

search route + pagination function

2023-05-23 11:16 UTC, BohdanSizomin requested changes

2023-05-23 11:16 UTC, BohdanSizomin commented on tests/test_routes/test_job.py
> +    assert response.status_code == 200
status code ... from fastapi

2023-05-24 08:36 UTC, BohdanSizomin approved these changes

2023-05-24 10:10 UTC, kipod reviewed
Looks good

2023-05-24 10:10 UTC, kipod commented on tests/test_routes/test_job.py
> +from sqlalchemy import select
```python
import sqlalchemy as sa
from sqlalchemy import orm
```

2023-05-24 10:10 UTC, kipod commented on tests/test_routes/test_job.py
> +    response = client.get("api/job/search", params={"city": f"{job.city}"})
:) 
```python
response = client.get("/api/job/search", params=dict(city=job.city))
```

2023-05-24 13:08 UTC, merged